title: Profile
url: "https://nmar2.github.io"
baseurl: "/profile"

description: "Professional profileof Nicola Marinelli, experienced Business Analyst, Project Manager, Data Analyst, competences in UML, BPMN, Agile, Python."

tracking_id: #

footer: yes
footer_url: "https://github.com/nmar2"
footer_text: "Page design by Nicola Marinelli"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/profile/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Certifications"
   link: "certifications"
 - name: "References"
   link: "references"   
 - name: "Contact"
   link: "contact"
